### PR TITLE
Testsuite: Make tomcat version configurable, add CI basic test for each version, minor tweaks and fixes

### LINKED ISSUE #131: Testsuite: parametrized tests with supported Tomcat versions
Just the same smoke test (config, autodeploy, status, etc) with different containers would be plenty for now.

### PR DESCRIPTION
**Pull request by jajik**
close #131

### CODE REVIEW

**Review by rhusar — COMMENTED** [review]
So again, great idea, but I am not sure if this is a good fit. In case you want to run this locally, you need to run the testsuite 3x with different parameter. I am under impression that the end goal is running a single command locally to be able to verify with all tests and the same command is then run on CI.

**Comment by jajik** [comment]
Hm, you're right. I intended this as a smoke test into CI, but I guess having an easy option of running this locally would be nice too. I'll change it. Thanks.

**Comment by jajik** [comment]
It's done. I also enabled the whole test suite and made a few fixes.

**Comment by rhusar** [comment]
@jajik This will now need a rebase (final one hopefully!)

**Comment by jajik** [comment]
Around one hour of runtime is expected with the current settings (it can be tweaked using environment variables as we do in `ci.yml`).

**Comment by jajik** [comment]
@rhusar  Rebase is done.

**Review by rhusar — APPROVED** [review]
LGTM!

**Comment by rhusar** [comment]
Oh, just to note @jajik these should perhaps use different set of configs, but we don't have to do it right now - https://github.com/modcluster/mod_proxy_cluster/issues/141

**Comment by jajik** [comment]
@rhusar Thanks for the review and merge!

**Pull request merged**
