### PR TITLE
Rework test without ci

### PR DESCRIPTION
**Pull request by jajik**
This is the first part of work for #112.

### CODE REVIEW

**Comment by jajik** [comment]
Just a note: If you want to run it locally, change line 15 of `test/MODCLUSTER-755/mcmps.sh`  (I should change the name here too...) from

> https://raw.githubusercontent.com/modcluster/mod_proxy_cluster/main/test/native/MODCLUSTER-755/mod_proxy_cluster.conf

to

> https://raw.githubusercontent.com/modcluster/mod_proxy_cluster/main/test/native/MODCLUSTER-734/mod_proxy_cluster.conf

or

> https://raw.githubusercontent.com/jajik/mod_proxy_cluster/rework-test-without-ci/test/MODCLUSTER-755/mod_proxy_cluster.conf

so that it won't fail while getting the conf file.

**Comment by jajik** [comment]
It's nearly ready. If there's anybody interested and wants to try it out, it is necessary to change urls in all CONF files to the current old structure (or change the repo/branch to this PR).

**Comment by jajik** [comment]
Alright, so this is ready for the review!

Bear in mind that paths are in such a way we want them to be in main branch – this means that they do not work currently and you have to change them locally if you want to test it (please do so). That means:

* set `MPC_CONF` variable to the current CONF location, i.e., `https://raw.githubusercontent.com/modcluster/mod_proxy_cluster/main/test/httpd/mod_proxy_cluster.conf`
* edit `MODCLUSTER-XYZ/testit.sh` files to contain `https://raw.githubusercontent.com/modcluster/mod_proxy_cluster/main/test/native/MODCLUSTER-XYZ/mod_proxy_cluster.conf` (there is additional `native` directory in the path). For MODCLUSTER-755, use MODCLUSTER-734 conf file as there is no conf file for the former at the moment

Everything else should be fine (or more accurately I can't think of anything else at the moment) and there are updated READMEs too, so that should help.

**Comment by jajik** [comment]
Additionally, I tweaked httpd's README, I moved tomcat container stuff into a separate directory (to be consistent with the httpd), and I made some minor tweaks in test for MODCLUSTER-785.

**Comment by jajik** [comment]
I'm now working on CI support and in order to ease merging of it, I updated the conf file with CI's IP (beside that, I cleaned it a bit too).

**Review by jfclere — APPROVED** [review]

**Comment by rhusar** [comment]
Since this is deleting all the Java-based tests – does that mean that all those tests are rewritten? Perhaps have you @jajik done a brief analysis that we are losing any coverage?

**Comment by jajik** [comment]
> Since this is deleting all the Java-based tests – does that mean that all those tests are rewritten? Perhaps have you @jajik done a brief analysis that we are 'losing' any coverage? (and 'losing' is an overstatement here since they aren't run now anyway)

No, they are not rewritten.

I was not able to get it running, but I did not make an analysis. It seemed that some tests were duplicated in what was rewritten, and some are going to be lost (e.g., MODCLUSTER-349), but since it was not used at all, I let it be. You're right that some kind of analysis would be warranted...

What I propose is to merge what we have (if you have no issue with it, of course) and create a new issue. I'll go through the java part and eventually rewrite it in "the new way" if it'll make sense. Does it seem reasonable to you?

**Comment by jajik** [comment]
> > Since this is deleting all the Java-based tests – does that mean that all those tests are rewritten? Perhaps have you @jajik done a brief analysis that we are 'losing' any coverage? (and 'losing' is an overstatement here since they aren't run now anyway)
> 
> No, they are not rewritten.
> 
> I was not able to get it running, but I did not make an analysis. It seemed that some tests were duplicated in what was rewritten, and some are going to be lost (e.g., MODCLUSTER-349), but since it was not used at all, I let it be. You're right that some kind of analysis would be warranted...
> 
> What I propose is to merge what we have (if you have no issue with it, of course) and create a new issue. I'll go through the java part and eventually rewrite it in "the new way" if it'll make sense. Does it seem reasonable to you?

^^ @rhusar

**Comment by rhusar** [comment]
> > > Since this is deleting all the Java-based tests – does that mean that all those tests are rewritten? Perhaps have you @jajik done a brief analysis that we are 'losing' any coverage? (and 'losing' is an overstatement here since they aren't run now anyway)
> > 
> > 
> > No, they are not rewritten.
> > I was not able to get it running, but I did not make an analysis. It seemed that some tests were duplicated in what was rewritten, and some are going to be lost (e.g., MODCLUSTER-349), but since it was not used at all, I let it be. You're right that some kind of analysis would be warranted...
> > What I propose is to merge what we have (if you have no issue with it, of course) and create a new issue. I'll go through the java part and eventually rewrite it in "the new way" if it'll make sense. Does it seem reasonable to you?
> 
> ^^ @rhusar

Yes, that's fine doing this as a post-merge task as it doesn't look like there is inclination to develop and use Java-based tests here.

**Comment by rhusar** [comment]
@jajik One last rebase please and I ll merge this today :-)

**Comment by jajik** [comment]
> @jajik One last rebase please and I ll merge this today :-)

Sure thing, it's done. Thanks!

**Comment by jajik** [comment]
fyi I've just updated two comparisons in `JBCS-1236/testit.sh` and `curlloop.sh` so that it works outside of bash too.

**Review by rhusar — APPROVED** [review]
Looks good to me, thanks for the work on this @jajik, move in the right direction.

There is a couple things that will need addressing eventually:

1. reviewing the removed java coverage (issue already open)
1. there should be no references to github from the testsuite, e.g. MPC_CONF, it must use the file from local checkout
1. same for quay - use local images, don't require publishing a test image
1. the custom test orchestration framework should be replaced by something more standard / proper testing framework, e.g. https://github.com/bats-core/bats-core
1. repos such as jfclere/httpd_websocket should either be embedded here or moved under modcluster org on GH

Let's discuss these later and focus on getting this running on CI.

**Pull request merged**
