### PR TITLE
MODCLUSTER-622 segfault in process_info

### PR DESCRIPTION
**Pull request by hokuda**

### CODE REVIEW

**Comment by Karm** [comment]
Can one of the admins verify this patch?

**Comment by rhusar** [comment]
This is ok to test.

**Comment by rhusar** [comment]
@Karm Could we fix the account that the CI integration uses? We have https://github.com/modcluster-pull-request for that.

**Comment by jfclere** [comment]
It is still not prefect: The apr_time_now(); I would rather do it before the the lock and have a local variable in the routine and set it in inside the loop.

**Comment by hokuda** [comment]
@jfclere Thanks for the suggestion. If the last one is ok, I will rebase.

**Pull request merged**
