### PR TITLE
[JBCS-634] decrease loops per vhosts for balancer changes

### PR DESCRIPTION
**Pull request by aogburn**
https://issues.jboss.org/browse/JBCS-634

### CODE REVIEW

**Comment by rhusar** [comment]
run_tests

**Comment by rhusar** [comment]
run tests

**Comment by rhusar** [comment]
Thanks @Karm

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
No sure why this is suddenly a problem
```
C:\workspace\workspace\mod_proxy_cluster-2.x-windows\DISTRO\
apache-lounge\label\w2k12r2\mod_proxy_cluster\native\mod_proxy_cluster\
mod_proxy_cluster.c(28): fatal error C1083: 
Cannot open include file: 'apr_strings.h': No such file or directory
```

Fails on master too though.  Checking...

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
@aogburn @rhusar The only change I did was to switch from building with [ApacheLounge httpd](http://www.apachelounge.com/download/) to building with our own [httpd](https://ci.modcluster.io/job/httpd-windows/).

I suppose the packaging of ApacheLounge has changed, perhaps due to APR update and it no longer provides what I need for mod_proxy_cluster in the way I expect.

This PR did not break the smoke test. I'll look into Apache Lounge httpd next week...

**Comment by rhusar** [comment]
@jfclere @Karm Not overly happy with this merge, really. First, it clearly duplicates code with add_balancers_workers function. An effort should be made to make the code manageable. Moreover, we require fixes to have an associated MODCLUSTER tracker, which this one does not, thus falls out of release notes and so on.

**Pull request merged**
