### PR TITLE
Ci workaround ignored paths

### PR DESCRIPTION
**Pull request by jajik**
followup for #248 and #246

### CODE REVIEW

**Comment by jajik** [comment]
The pipeline will be failing until we merge #250

**Review by rhusar — CHANGES_REQUESTED** [review]
LOL, thanks for the hack demonstration, this would work. But oh man, 50 LOC hack to manage just to solve a non-existent problem is not great use of our time. 

Let me try couple of other things, if not, I ll revert the original change.

**Review by rhusar — APPROVED** [review]
Lets try this until GH fixes this (even though it's been long time in the making).

**Comment by rhusar** [comment]
BTW I did toy around with the idea of creating a first step to get list of all changes files, if they match any of these, then skip the following jobs. But that's more error prone than this approach, so I scratched that.

**Comment by jajik** [comment]
> Lets try this until GH fixes this (even though it's been long time in the making).

You mean like this one https://github.com/orgs/community/discussions/12032 ? :smiley:

**Comment by jajik** [comment]
Thanks for the merge

**Comment by rhusar** [comment]
> > Lets try this until GH fixes this (even though it's been long time in the making).
> 
> You mean like this one https://github.com/orgs/community/discussions/12032 ? 😃

The rebase button is crap - that invalidates signing information. Using a merge commit in turn adds a lot of noise with merge commits. Sigh..

**Pull request merged**
