### PR TITLE
Fix tomcat ports overlapping

### LINKED ISSUE #132: Testsuite: all Tomcat ports needs to be offset, not just 8080
Given these use host networking, the ajp connector port needs to be offset as well.

```
10-Aug-2023 11:20:54.790 SEVERE [main] org.apache.catalina.core.StandardService.initInternal Failed to initialize connector [Connector[AJP/1.3-8009]]
	org.apache.catalina.LifecycleException: Protocol handler initialization failed
		at org.apache.catalina.connector.Connector.initInternal(Connector.java:1075)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
		at org.apache.catalina.core.StandardService.initInternal(StandardService.java:559)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
		at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:854)
		at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:136)
		at org.apache.catalina.startup.Catalina.load(Catalina.java:646)
		at org.apache.catalina.startup.Catalina.load(Catalina.java:669)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
		at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
		at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.base/java.lang.reflect.Method.invoke(Method.java:568)
		at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:307)
		at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:477)
	Caused by: java.net.BindException: Address already in use
		at java.base/sun.nio.ch.Net.bind0(Native Method)
		at java.base/sun.nio.ch.Net.bind(Net.java:555)
		at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
		at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
		at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
		at org.apache.tomcat.util.net.NioEndpoint.initServerSocket(NioEndpoint.java:226)
		at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:202)
		at org.apache.tomcat.util.net.AbstractEndpoint.bindWithCleanup(AbstractEndpoint.java:1318)
		at org.apache.tomcat.util.net.AbstractEndpoint.init(AbstractEndpoint.java:1331)
		at org.apache.tomcat.util.net.AbstractJsseEndpoint.init(AbstractJsseEndpoint.java:231)
		at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:693)
		at org.apache.catalina.connector.Connector.initInternal(Connector.java:1073)
		... 13 more
```

### PR DESCRIPTION
**Pull request by jajik**
close #132

### CODE REVIEW

**Review by rhusar — APPROVED** [review]
LGTM

**Comment by rhusar** [comment]
Merged, thanks @jajik

**Comment by jajik** [comment]
Thanks @rhusar

**Comment by jajik** [comment]
I'll have to look into it, because this PR also added the ability to set ports directly which might cause some problems too (what if I want to offset only some? I'll have a look).

**Comment by rhusar** [comment]
> I'll have to look into it, because this PR also added the ability to set ports directly which might cause some problems too (what if I want to offset only some? I'll have a look).

OK - opened https://github.com/modcluster/mod_proxy_cluster/issues/140

**Pull request merged**
