### PR TITLE
do not merge, test to be removed

### PR DESCRIPTION
**Pull request by Karm**
do not merge, test to be removed

### CODE REVIEW

**Comment by Karm** [comment]
test

**Comment by Karm** [comment]
test

**Comment by Karm** [comment]
test

**Comment by Karm** [comment]
test

**Comment by Karm** [comment]
run test

**Comment by Karm** [comment]
run test

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
Can one of the admins verify this patch?

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
Can one of the admins verify this patch?

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
@jfclere @rhusar @pferraro The green ☑️ means mod_proxy cluster was fetched, compiled with apache-lounge httpd *both* for 32 and 64 bit and [smoke tested](https://github.com/modcluster/ci.modcluster.io/blob/master/windows/mod_proxy_cluster/build.bat#L124). All that in 1m 49 seconds (sequential run, 32b first, 64b second).  I aim to push it well under a minute and perhaps limit to just 64 bit build. Build with [JBoss http](https://ci.modcluster.io/job/httpd-windows/41/) is on TODO, there is no blocker, just haven't finished the script yet. Stay tuned for updates & README.

**Comment by rhusar** [comment]
@Karm Is it necessary to type "run tests" every time? Can this be automated?

**Comment by rhusar** [comment]
@Karm Also it seems the statuses are posted from your account (Karm), if htat's the case can you update this to our CI account, https://github.com/modcluster-pull-request ?

**Pull request closed without merging**
