### PR TITLE
Test suite improvements

### PR DESCRIPTION
**Pull request by jajik**
I went through the test suite and made some changes. Mainly

* change formatting of `tests.sh` script, renamed some functions, and fixed bugs
* updated httpd container image used in tests (it was not working)
* updated README

There is space for more improvements, mainly separating individual tests to be able to run them separately, but that's something for the future.

### CODE REVIEW

**Review by jfclere — COMMENTED** [review]
Why are you using 8.5?

**Review by jfclere — COMMENTED** [review]
sed -i -e 's/LogLevel warn/LogLevel debug/g' /usr/local/apache2/conf/httpd.conf

Please Don't :D

**Comment by jajik** [comment]
Good catch. I had an issue with Tomcat 9, those jsp files tests result in 404, older tomcat worked fine. (And then forgot about it. I'll have a look.)

> Please Don't :D

I found it useful for an image dedicated to testing, but ok, I'll remove it.

**Review by jfclere — APPROVED** [review]

**Review by rhusar — APPROVED** [review]
Generally looks good to me.

**Pull request merged**
