### PR TITLE
Fix an error message to contain the correct directive name

### PR DESCRIPTION
**Pull request by jajik**
There is a typo/error in the error message: *for* -> *before*.

### CODE REVIEW

**Review by jfclere — APPROVED** [review]

**Comment by jajik** [comment]
Thanks for the review

**Comment by rhusar** [comment]
Interestingly enough, the https://docs.modcluster.io/legacy/ mention the old variant but https://docs.modcluster.io/#waitbeforeremove is correct.

**Comment by jfclere** [comment]
@rhusar do you want to support both version? or assume we are good?

**Comment by jajik** [comment]
I've just quickly scanned the repo and it seems the directive was always `WaitBeforeRemove` and that the docs were simply wrong. At least that's how it looks like.

**Pull request merged**
