### PR TITLE
MODCLUSTER-822: Decline Contexts and Aliases if lengths are exceeded

### PR DESCRIPTION
**Pull request by jajik**
ref [MODCLUSTER-822](https://issues.redhat.com/browse/MODCLUSTER-822)

This approach abstracts processing of Alias and Context for both APP and CONFIG commands. As a result, Alias for CONFIG is now also case insensitive, but that seems more like the correct behavior...

### CODE REVIEW

**Review by jfclere — APPROVED** [review]
Looks OK for me.

**Comment by jfclere** [comment]
Any plans to add tests for the new messages? ;-)

**Comment by jajik** [comment]
> Any plans to add tests for the new messages? ;-)

I hope that I'll manage to add the httpd/perl framework soon and write tests in that. I added this PR to the Missing tests issue.

**Comment by jajik** [comment]
Merging. Thanks for the review!

**Pull request merged**
