### PR TITLE
Run clang-format in CI

### PR DESCRIPTION
**Pull request by jajik**
Now, when styles are merged, we can run automatic checks. Also, I added a note into README.

You can check how it looks like in CI
* passed https://github.com/jajik/mod_proxy_cluster/actions/runs/4925250133/jobs/8799244223
* failed https://github.com/jajik/mod_proxy_cluster/actions/runs/4925218550/jobs/8799176093

### CODE REVIEW

**Comment by jajik** [comment]
(Changed the commit message: `clang-tidy` -> `clang-format`.)

**Comment by jajik** [comment]
@rhusar  I did fix it, but in another branch. I'll cherry-pick it here.

**Review by rhusar — APPROVED** [review]
Looks good. 

n.b. Though looking at the problematic style that are line length related, I gotta say, I am not a huge fan myself of artificial limits (`ColumnLimit: 120` (and yes, still better than 80 LOL)), but I guess it's more common with apache codebase.

**Comment by jajik** [comment]
We can drop it eventually, or use `/* clang-format off/on */` as stated in readme. (In many cases, they don't hold the 80 characters limit.)

**Pull request merged**
