### PR TITLE
ci: Tweak ci so it doesn't run without meaningful changes

### PR DESCRIPTION
**Pull request by jajik**
It occurred to me that we run CI on all commits regardless the changes. This PR will cause CI running only if anything within the CI file, or `native/`, `test/` directories changes.

### CODE REVIEW

**Review by rhusar — CHANGES_REQUESTED** [review]
So no verifying building docs when Doxyfile is changed? :)

**Comment by jajik** [comment]
> So no verifying building docs when Doxyfile is changed? :)

Fixed.

**Review by rhusar — CHANGES_REQUESTED** [review]
Still not a great approach. Going forward, we would need to keep in mind that adding new paths need to be added for CI scripts.

Rather than selecting which files to run the build for, we can just label the ones that definitely do not effect the build.

Opened https://github.com/modcluster/mod_proxy_cluster/pull/248

**Comment by rhusar** [comment]
For example, this would still run tests for `tests/README.md`. Closing in favor of https://github.com/modcluster/mod_proxy_cluster/pull/248

**Pull request closed without merging**
