### PR TITLE
CI: Change package name for docker

### PR DESCRIPTION
**Pull request by jajik**
For some reason the current way stopped working (e.g., [here](https://github.com/modcluster/mod_proxy_cluster/actions/runs/5852618025/job/16318039134?pr=137)).

### CODE REVIEW

**Comment by rhusar** [comment]
Well, you can't say they didn't warn you! Right at the top of the log:

> WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

**Comment by jajik** [comment]
Well, that's not the issue, `moby-*` -> `docker` is. I changed the `apt` to get rid off the warning. :)

**Review by rhusar — APPROVED** [review]
LGTM, thanks. I wasn't even familiar with the moby package.

**Comment by rhusar** [comment]
Thanks @jajik

**Pull request merged**
