### PR TITLE
Polish configs, minor improvements for the testsuite

### PR DESCRIPTION
**Pull request by jajik**

### CODE REVIEW

**Comment by jajik** [comment]
The cleanup is especially necessary in cases where mod_cluster gets updated in the meantime (i.e., tests have multiple mod_cluster jars from which to choose). ref #176

**Review by jfclere — APPROVED** [review]

**Comment by rhusar** [comment]
@jajik What is 'Remvove'? :-D

**Review by rhusar — APPROVED** [review]
Other than that, lgtm.

**Comment by jajik** [comment]
> @jajik What is 'Remvove'? :-D

Well, that's a nice typo. :D It's fixed, thanks for the catch.

**Pull request merged**
