### PR TITLE
Record presence/absence of workers within node (#179)

### LINKED ISSUE #179: Record presence/absence of workers within node
We should replace `node_has_workers` with an attribute within node's structure.

### PR DESCRIPTION
**Pull request by jajik**
close #179 

Also, this will require updating apidocs.

### CODE REVIEW

**Comment by rhusar** [comment]
@jfclere Please review.

**Review by jfclere — COMMENTED** [review]
Are we sure the node table is looked when using pair_worker_node()/unpair_worker_node()
I would put the if (ou->mess.has_workers > 0) in a function in case we need to use apr atomic at some point.

**Comment by jajik** [comment]
> Are we sure the node table is looked when using pair_worker_node()/unpair_worker_node()?

One call was not called, it should be fixed now.

> I would put the if (ou->mess.has_workers > 0) or any read to has_worker in a function in case we need to use apr atomic at some point.

That's a good point. I reintroduced `node_has_workers` function. The rest of the accesses happens within pair/unpair functions. I left that as is.

**Review by jfclere — APPROVED** [review]

**Comment by jajik** [comment]
Merging, thanks for the review.

**Pull request merged**
