### PR TITLE
Unify style of comments, improve function description

### LINKED ISSUE #158: Unify style of comments before function declaration/definition.
See [this comment](https://github.com/modcluster/mod_proxy_cluster/pull/153#discussion_r1368695904)

### PR DESCRIPTION
**Pull request by jajik**
Work in progess but it should give the idea.

close #158

### CODE REVIEW

**Review by jfclere — CHANGES_REQUESTED** [review]
Don't remove comments.
The rest looks OK for me.

**Comment by rhusar** [comment]
> Don't remove comments. The rest looks OK for me.

Well, the comments are moved from implementation to the header file, that appears correct to me.

**Comment by jajik** [comment]
Good, thank you both! I'll continue with the rest.

**Comment by jajik** [comment]
@jfclere Marking Ready for review.

Comments are updated. I added a Doxyfile and a note into the README about how to build doxygen docs. Once we merge this I will add those docs on the web as [Radoslav suggested](https://github.com/modcluster/mod_proxy_cluster/issues/161#issuecomment-1780926977).

**Review by rhusar — APPROVED** [review]
LGTM

**Comment by rhusar** [comment]
Thanks @jajik for cleaning this up and @jfclere

**Comment by jajik** [comment]
Thanks!

**Pull request merged**
