### PR TITLE
Fix for MODCLUSTER-721

### PR DESCRIPTION
**Pull request by jfclere**
That removes the messup with the good mod_proxy default values.

### CODE REVIEW

**Comment by jfclere** [comment]
retest this please

**Comment by rhusar** [comment]
@dsartzet Please don't forget to resolve the issue in Jira upon merge and set/verify the fix version!

**Comment by dsartzet** [comment]
> @dsartzet Please don't forget to resolve the issue in Jira upon merge and set/verify the fix version!

You're right! I see you did already, thanks @rhusar  :+1:

**Comment by rhusar** [comment]
Although looking at it, the PRs have not been linked (upstream-downstream @jfclere so please do that) and also these should be merged at the same time otherwise it will fall through the cracks and cause regression upstream... so please keep an eye on that.

**Comment by rhusar** [comment]
I might actually add a GitHub PR template so that people remember that.

**Comment by jfclere** [comment]
downstream 1.3.x commit: https://github.com/modcluster/mod_cluster/pull/457/commits/2e38626cc4a9d1cbecc6d9dc3c9024a49da6e636

**Pull request merged**
