### PR TITLE
Remove unused out-of-date file.

### PR DESCRIPTION
**Pull request by rhusar**

### CODE REVIEW

**Comment by jajik** [comment]
Does it make sense to remove other files too? Namely

* `local.properties`
* `test-jars.xml`
* `build-test.xml`

If we want to go big, we could remove the whole `test/java` part and then flatten the structure from `test/native` to `test`.

**Comment by rhusar** [comment]
> Does it make sense to remove other files too? Namely
> 
> * `local.properties`
> * `test-jars.xml`
> * `build-test.xml`
> 
> If we want to go big, we could remove the whole `test/java` part and then flatten the structure from `test/native` to `test`.

We should have a discussion for cleaning  those up or updating. But this deletion is out of that scope, these instructions are purely out of date and useless.

**Comment by jajik** [comment]
Ok.

**Comment by rhusar** [comment]
Thanks @jajik

**Pull request merged**
