### PR TITLE
MODCLUSTER-591 MemManagerFile should not default to server_root + "/l…

### PR DESCRIPTION
**Pull request by rhusar**
…ogs"

### CODE REVIEW

**Comment by Karm** [comment]
@rhusar I'm not 100% convinced this is enough to make it better. Take a look into ```create_attach_mem_node``` and on, e.g. ```ap_log_error(APLOG_MARK, APLOG_NOERRNO|APLOG_EMERG, 0, s, "get_mem_node %s failed", node);``` messages.   It would be great if it suggests user using ```MemManagerFile``` to specify an existing directory...    WDYT?

**Comment by Karm** [comment]
test

**Comment by Karm** [comment]
test

**Comment by Karm** [comment]
run tests

**Comment by jfclere** [comment]
actually the default httpd doesn't have cache, so the fix doesn't look like a good idea.

**Pull request closed without merging**
