### PR TITLE
CI: skip checks on files which do not effect the build nor tests such…

### PR DESCRIPTION
**Pull request by rhusar**
… as markdown files

Replaces https://github.com/modcluster/mod_proxy_cluster/pull/247

### CODE REVIEW

**Review by jajik — COMMENTED** [review]
What about `.gitattributes` and `.github/dependabot.yml`?

**Comment by rhusar** [comment]
> What about `.gitattributes` and `.github/dependabot.yml`?

The .gitattributes has direct effect what the checkout looks like and effects the build. 

The dependabot.yml changes are being checked for PRs and I am not sure if ignoring it here wouldn't break those checks.

**Comment by jajik** [comment]
Ok

**Comment by jajik** [comment]
Merging now. Thanks.

**Pull request merged**
