### PR TITLE
Patch BZ 1448709 / MODCLUSTER-582 by Martin Osvald

### PR DESCRIPTION
**Pull request by Karm**
SSIA
TODO:
 * 1.3.x
 * 1.2.x
 * Use LLVM toolchain or Visual Studio to find similar issues

### CODE REVIEW

**Comment by Karm** [comment]
run tests

**Comment by Karm** [comment]
(the first automatic execution failed due to disconnected slave, again...)

**Comment by jfclere** [comment]
https://github.com/modcluster/mod_proxy_cluster/pull/17

**Comment by Karm** [comment]
@jfclere Facepalm.

**Pull request closed without merging**
